#!/usr/bin/sh
set -e
kernel_params="$(sed -e 's/ /\n/g' < /proc/cmdline)"
get_kparam() {
	sed -e '/^'"${1}"='/!d' -e 's/^'"${1}"'=//g' <<EOF
${kernel_params}
EOF
}
get_kparam_set() {
	sed -e '/^'"${1}"'$/!d' <<EOF
${kernel_params}
EOF
}
KP_NAME="secure_squash_root"
SLOT="$(get_kparam "${KP_NAME}_slot")"
ROOTHASH="$(get_kparam "${KP_NAME}_hash")"
VOLATILE="$(get_kparam_set "${KP_NAME}_volatile")"
ROOT="${1}"
DEST="${2}"
TMP="/secure-squashfs-tmp"
if [ "${VOLATILE}" = "${KP_NAME}_volatile" ]; then
	OLROOT="${TMP}/tmpfs"
	mount -t tmpfs tmpfs "${OLROOT}"
else
	OLROOT="${ROOT}"
fi

mkdir -p "${OLROOT}/overlay" "${OLROOT}/workdir"
IMAGE="${ROOT}/image_${SLOT}.squashfs"
veritysetup open "${IMAGE}" rootsq "${IMAGE}.verity" "${ROOTHASH}"
mount -o ro "/dev/mapper/rootsq" "${TMP}/squashroot"
# Remove modules and use them from squashfs
# This avoids module loading problems due to kernel version mismatch
rm -rf "${ROOT}/overlay/usr/lib/modules/$(uname -r)/kernel/"
# Disable index and metacopy, so the underlying filesystem can be updated
# Metacopy also has security problems on untrusted upper (See kernel overlayfs)
mount \
	-t overlay overlay \
	-o lowerdir="${TMP}/squashroot" \
	-o upperdir="${OLROOT}/overlay" \
	-o workdir="${OLROOT}/workdir" \
	-o index=off,metacopy=off \
	"${DEST}"
