#!/usr/bin/sh
fingerprint() {
	openssl x509 -in "${1}" -noout -fingerprint
	openssl x509 -in "${1}" -noout -fingerprint -sha256
}
uuidgen --random > guid.txt
UUID="$(cat guid.txt)"
create_key() {
	openssl req -newkey rsa:4096 -nodes -keyout "${1}.key" -new -x509 \
		-sha256 -days 3650 -subj "/CN=${2}/" -out "${1}.crt"
	fingerprint "${1}.crt" > "${1}.hash"
	openssl x509 -outform DER -in "${1}.crt" -out "${1}.cer"
	cert-to-efi-sig-list -g "${UUID}" "${1}.crt" "${1}.esl"
}

create_key pk "Platform Key"
sign-efi-sig-list -g "${UUID}" -k pk.key -c pk.crt pk pk.esl pk.auth
sign-efi-sig-list -g "${UUID}" -c pk.crt -k pk.key pk /dev/null rm_pk.auth

create_key kek "Key Exchange Key"
sign-efi-sig-list -g "${UUID}" -k pk.key -c pk.crt kek kek.esl kek.auth

create_key db "Signature Database Key"
sign-efi-sig-list -g "${UUID}" -k kek.key -c kek.crt db db.esl db.auth
