#!/usr/bin/sh
set -e
kernel_params="$(sed -e 's/ /\n/g' < /proc/cmdline)"
get_kparam() {
	sed -e '/^'"${1}"='/!d' -e 's/^'"${1}"'=//g' <<EOF
${kernel_params}
EOF
}
get_kparam_set() {
	sed -e '/^'"${1}"'$/!d' <<EOF
${kernel_params}
EOF
}
KP_NAME="verity_squash_root"
SLOT="$(get_kparam "${KP_NAME}_slot")"
ROOTHASH="$(get_kparam "${KP_NAME}_hash")"
VOLATILE="$(get_kparam_set "${KP_NAME}_volatile")"
ROOT="${1}"
DEST="${2}"
TMP="/verity-squash-root-tmp"
if [ "${VOLATILE}" = "${KP_NAME}_volatile" ]; then
	OLROOT="${TMP}/tmpfs"
	mount -t tmpfs tmpfs "${OLROOT}"
	# Print date so rollback attacks can be detected
	printf "You are booting a tmpfs overlay built at "
	cat "/VERITY_SQUASH_ROOT_DATE"
	printf "Press enter to continue\\n"
	read -r _
else
	OLROOT="${ROOT}"
fi

# workdir needs to be an empty directory, otherwise there can be file corruption
rm -rf "${OLROOT}/workdir"
mkdir -p "${OLROOT}/overlay" "${OLROOT}/workdir"
IMAGE="${ROOT}/image_${SLOT}.squashfs"
veritysetup open "${IMAGE}" rootsq "${IMAGE}.verity" "${ROOTHASH}"
mount -o ro "/dev/mapper/rootsq" "${TMP}/squashroot"
# Disable xino, index and metacopy, so the underlying filesystem can be updated
# Metacopy also has security problems on untrusted upper (See kernel overlayfs)
mount \
	-t overlay overlay \
	-o lowerdir="${TMP}/squashroot" \
	-o upperdir="${OLROOT}/overlay" \
	-o workdir="${OLROOT}/workdir" \
	-o index=off,metacopy=off,xino=off \
	"${DEST}"
