#!/usr/bin/sh
set -e
. /usr/lib/verity-squash-root/functions
SLOT="$(get_kparam "${KP_NAME}_slot")"
ROOTHASH="$(get_kparam "${KP_NAME}_hash")"
VOLATILE="$(get_kparam_set "${KP_NAME}_volatile")"
ROOT="${1}"
DEST="${2}"
TMP="/verity-squash-root-tmp"
if [ "${VOLATILE}" = "${KP_NAME}_volatile" ]; then
	OLROOT="${TMP}/tmpfs"
	mount -t tmpfs tmpfs "${OLROOT}"
else
	OLROOT="${ROOT}"
fi

# workdir needs to be an empty directory, otherwise there can be file corruption
rm -rf "${OLROOT}/workdir"
mkdir -p "${OLROOT}/overlay" "${OLROOT}/workdir"
IMAGE="${ROOT}/image_${SLOT}.squashfs"
veritysetup open "${IMAGE}" rootsq "${IMAGE}.verity" "${ROOTHASH}"
mount -o ro "/dev/mapper/rootsq" "${TMP}/squashroot"
# Disable xino, index and metacopy, so the underlying filesystem can be updated
# Metacopy also has security problems on untrusted upper (See kernel overlayfs)
mount \
	-t overlay overlay \
	-o lowerdir="${TMP}/squashroot" \
	-o upperdir="${OLROOT}/overlay" \
	-o workdir="${OLROOT}/workdir" \
	-o index=off,metacopy=off,xino=off \
	"${DEST}"
