#!/bin/bash

build() {
	add_binary mount
	add_binary uname
	add_binary veritysetup
	add_dir /overlayroot
	add_dir /secure-squashfs-tmp/squashroot
	add_dir /secure-squashfs-tmp/tmpfs
	add_file "/usr/lib/secure-squash-root/mount_handler"
	add_module dm_mod
	add_module dm_verity
	add_module loop
	add_module overlay
	add_module squashfs

	rootfs="$(findmnt -uno fstype -T /mnt/root)"
	add_module "${rootfs}"
	add_binary "fsck.${rootfs}"

	if type add_systemd_unit &> /dev/null; then
		# add_systemd_unit otpboot.service
		cat <<EOF | add_systemd_drop_in initrd-switch-root.service squashroot
[Service]
ExecStart=
ExecStart=sh /usr/lib/secure-squash-root/mount_handler /sysroot /overlayroot
ExecStart=systemctl --no-block switch-root /overlayroot
EOF
	else
		add_runscript
	fi
}

help() {
	cat <<HELPEOF
INFO
HELPEOF
}
