#!/bin/bash

build() {
	add_binary mount
	add_binary uname
	add_binary veritysetup
	add_dir /overlayroot
	add_dir /verify-squashfs-tmp/squashroot
	add_dir /verify-squashfs-tmp/tmpfs
	add_file "/usr/lib/verify-squash-root/mount_handler"
	add_module dm_mod
	add_module dm_verity
	add_module loop
	add_module overlay
	add_module squashfs

	rootfs="$(findmnt -uno fstype -T /mnt/root)"
	add_module "${rootfs}"
	add_binary "fsck.${rootfs}"
	# autodetect with overlayfs does not work, so
	# set the rootfstype manually
	rootfstype="${rootfs}"

	if type add_systemd_unit &> /dev/null; then
		# add_systemd_unit otpboot.service
		cat <<EOF | add_systemd_drop_in initrd-switch-root.service squashroot
[Unit]
Requires=systemd-vconsole-setup.service
After=plymouth-start.service systemd-vconsole-setup.service

[Service]
# needed for read, when tmpfs is used
StandardInput=tty
StandardOutput=tty
TimeoutStartSec=infinity

ExecStart=
ExecStart=sh /usr/lib/verify-squash-root/mount_handler /sysroot /overlayroot
ExecStart=systemctl --no-block switch-root /overlayroot
EOF
	else
		add_runscript
	fi
}

help() {
	cat <<HELPEOF
INFO
HELPEOF
}
