#!/bin/bash

date_or_override() {
	# allow override for reproducible builds
	if [ "${DATE_OVERRIDE}" != "" ]; then
		printf "%s\\n" "${DATE_OVERRIDE}"
	else
		date "+%Y-%m-%d %H:%M:%S %Z"
	fi
}

build() {
	add_binary mount
	add_binary uname
	add_binary veritysetup
	add_dir /overlayroot
	add_dir /verify-squashfs-tmp/squashroot
	add_dir /verify-squashfs-tmp/tmpfs
	add_file "/usr/lib/verify-squash-root/mount_handler"
	date_or_override > "${BUILDROOT}/VERIFY_SQUASH_ROOT_DATE"

	add_module dm_mod
	add_module dm_verity
	add_module loop
	add_module overlay
	add_module squashfs

	if type add_systemd_unit &> /dev/null; then
		# add_systemd_unit otpboot.service
		cat <<EOF | add_systemd_drop_in initrd-switch-root.service squashroot
[Unit]
Requires=systemd-vconsole-setup.service
After=plymouth-start.service systemd-vconsole-setup.service

[Service]
# needed for read, when tmpfs is used
StandardInput=tty
StandardOutput=tty
TimeoutStartSec=infinity

ExecStart=
ExecStart=sh /usr/lib/verify-squash-root/mount_handler /sysroot /overlayroot
ExecStart=systemctl --no-block switch-root /overlayroot
EOF
	else
		add_runscript
	fi
}

help() {
	cat <<HELPEOF
INFO
HELPEOF
}
